In [ ]:
#矩陣做LU分解
def LU_decomposition(A):
    """
    對矩陣 A 進行 LU 分解，返回 L 和 U，
    其中 L 為單位下三角矩陣，U 為上三角矩陣。

    如果 A 為奇異矩陣（即 U[j][j] 為 0），則會引發 ZeroDivisionError。
    """
    n = len(A)
    # 初始化 L 和 U 為 n x n 的零矩陣
    L = [[0.0] * n for _ in range(n)]
    U = [[0.0] * n for _ in range(n)]

    # L 的對角線設定為 1
    for i in range(n):
        L[i][i] = 1.0

    # 依序計算 U 和 L 的各元素
    for j in range(n):
        # 計算 U 的第 j 列（i 從 0 到 j）
        for i in range(j + 1):
            sum_u = 0.0
            for k in range(i):
                sum_u += L[i][k] * U[k][j]
            U[i][j] = A[i][j] - sum_u

        # 計算 L 的第 j 列（i 從 j 到 n-1）
        for i in range(j, n):
            sum_l = 0.0
            for k in range(j):
                sum_l += L[i][k] * U[k][j]
            if abs(U[j][j]) < 1e-12:
                raise ZeroDivisionError("矩陣奇異，無法進行 LU 分解")
            L[i][j] = (A[i][j] - sum_l) / U[j][j]

    return L, U

# 範例：
A = [
    [4, 3],
    [6, 3]
]
L, U = LU_decomposition(A)
print("L =", L)
print("U =", U)

[[0.0, 0.0], [0.0, 0.0]] [[0.0, 0.0], [0.0, 0.0]]
L = [[1.0, 0.0], [1.5, 1.0]]
U = [[4.0, 3.0], [0.0, -1.5]]


In [ ]:
#矩陣做SVD分解
def

In [ ]:
#矩陣做QR分解(Gram-Schmidt正交化)
def QR_decomposition(A):
    """
    對矩陣 A 進行 QR 分解，返回 Q 和 R，
    其中 Q 為正交矩陣（m x n），R 為上三角矩陣（n x n），滿足 A = Q * R。

    參數:
        A: m x n 矩陣（以二維列表表示），假設 A 的列向量線性獨立。

    如果發現某列向量在投影後近似為零，將引發 ValueError 表示矩陣的列向量線性相關。
    """
    import math

    m = len(A)          # A 的行數
    n = len(A[0])       # A 的列數

    # 初始化 Q 為 m x n 的零矩陣，R 為 n x n 的零矩陣
    Q = [[0.0] * n for _ in range(m)]
    R = [[0.0] * n for _ in range(n)]

    # 對 A 的每一列進行 Gram-Schmidt 正交化
    for k in range(n):
        # 從 A 中取出第 k 列作為初始向量 v
        v = [A[i][k] for i in range(m)]
        # 對於每一個之前已求得的正交向量 q_j
        for j in range(k):
            # 計算 R[j][k] = q_j^T * a_k
            R[j][k] = sum(Q[i][j] * A[i][k] for i in range(m))
            # 從 v 中扣除在 q_j 上的分量
            for i in range(m):
                v[i] -= R[j][k] * Q[i][j]
        # 計算向量 v 的歐氏範數
        norm_v = math.sqrt(sum(v_i * v_i for v_i in v))
        if abs(norm_v) < 1e-12:
            raise ValueError("矩陣的列向量線性相關，無法進行 QR 分解")
        R[k][k] = norm_v
        # 將歸一化後的向量 v 作為 Q 的第 k 列
        for i in range(m):
            Q[i][k] = v[i] / norm_v

    return Q, R

# 範例使用：
A = [
    [1, 1],
    [1, -1],
    [1, 2]
]
Q, R = QR_decomposition(A)
print("Q =", Q)
print("R =", R)

Q = [[0.5773502691896258, 0.1543033499620918], [0.5773502691896258, -0.7715167498104596], [0.5773502691896258, 0.6172133998483674]]
R = [[1.7320508075688772, 1.1547005383792517], [0.0, 2.160246899469287]]


In [ ]:
#矩陣做QR分解(Householder轉換)(函數版本)
import numpy as np

# 定義一個矩陣 A
A = np.array([
    [1,  1],
    [1, -1],
    [1,  2]
], dtype=float)

# 使用 numpy.linalg.qr 進行 QR 分解
Q, R = np.linalg.qr(A)

print("Q =\n", Q)
print("R =\n", R)

Q =
 [[-0.57735027  0.15430335]
 [-0.57735027 -0.77151675]
 [-0.57735027  0.6172134 ]]
R =
 [[-1.73205081 -1.15470054]
 [ 0.          2.1602469 ]]


In [ ]:
#矩陣做QR分解(Householder轉換)(手科版本)
import numpy as np

def householder_qr(A):
    """
    利用 Householder 轉換對矩陣 A 進行 QR 分解，
    返回正交矩陣 Q 與上三角矩陣 R，使得 A = Q * R。
    """
    A = A.copy().astype(float)
    m, n = A.shape
    Q = np.eye(m)

    for k in range(n):
        # 提取第 k 列下方的向量 x
        x = A[k:, k]
        normx = np.linalg.norm(x)
        # 為了避免數值消除，決定符號
        s = -1 if x[0] >= 0 else 1
        # 構造 Householder 向量 v
        u = x.copy()
        u[0] -= s * normx
        v = u / np.linalg.norm(u)

        # 構造 Householder 矩陣 H = I - 2*v*v^T
        H = np.eye(m - k) - 2.0 * np.outer(v, v)
        # 將 H 擴展到 m 維的單位矩陣
        H_full = np.eye(m)
        H_full[k:, k:] = H

        # 更新 A 與 Q
        A = H_full @ A
        Q = Q @ H_full

    # A 此時已經變成上三角矩陣 R
    R = A
    return Q, R

# 範例使用：
A = np.array([
    [1,  1],
    [1, -1],
    [1,  2]
], dtype=float)

def householder_qr_reduced(A):
    Q_full, R_full = householder_qr(A)
    m, n = A.shape
    Q_reduced = Q_full[:, :n]  # 取前 n 列
    R_reduced = R_full[:n, :]  # 取前 n 行
    return Q_reduced, R_reduced

# 使用經濟型 QR 分解：
Q_red, R_red = householder_qr_reduced(A)
print("Q_reduced =\n", Q_red)
print("R_reduced =\n", R_red)


Q_reduced =
 [[-0.57735027  0.15430335]
 [-0.57735027 -0.77151675]
 [-0.57735027  0.6172134 ]]
R_reduced =
 [[-1.73205081 -1.15470054]
 [ 0.          2.1602469 ]]


In [ ]:
import numpy as np
import scipy.linalg as la

# 定義一個非奇異的 3x3 矩陣 A 和向量 b
A = np.zeros([4,4], dtype=float)
for i in range(len(A)):
  for j in range(len(A)):
    A[i][j] = 1/(i+j+1)
b = np.array([1, 1, 1, 1], dtype=float)

# ---------------------------
# 1. 利用 QR 分解求解 Ax = b
# ---------------------------
# 使用 NumPy 的 QR 分解（全 QR 分解，對於方陣可使用 reduced 模式或直接求解）
Q, R = np.linalg.qr(A)
# 由 A = Q * R，所以有 Q.T * b = R * x，故 x = R^{-1} * (Q.T * b)
x_qr = np.linalg.solve(R, Q.T @ b)
QR_residual = A @ x_qr - b

# ---------------------------
# 2. 利用 LU 分解求解 Ax = b
# ---------------------------
# 使用 SciPy 的 LU 分解：先進行 lu_factor 再用 lu_solve
lu, piv = la.lu_factor(A)
x_lu = la.lu_solve((lu, piv), b)
LU_residual = A @ x_lu - b

# ---------------------------
# 3. 利用 SVD 分解求解 Ax = b
# ---------------------------
# SVD 分解：A = U * Σ * V^T
U, s, Vh = np.linalg.svd(A)
# 由於 Σ 為對角矩陣，可以用反向 Σ 求解 x：
# 令 c = U^T * b，則有 Σ * (V^T * x) = c，因此 x = V * (1/Σ) * c
c = U.T @ b
w = c / s        # 等價於用對角矩陣 Σ 的逆乘 c
x_svd = Vh.T @ w
SVD_residual = A @ x_svd - b

# ---------------------------
# 計算條件數 (condition number)
# ---------------------------
# 以 2-範數為例，condition number 可由 SVD 分解得到：max(s) / min(s)
cond_A = np.linalg.cond(A)  # 或直接 cond_A = s.max()/s.min()


# ---------------------------
# boundary
# ---------------------------
LU_upper_bound = (cond_A)*np.linalg.norm(A @ x_lu - b,ord = 1)/np.linalg.norm(b)
print("LU_upper_bound:",LU_upper_bound)
QR_upper_bound = (cond_A)*np.linalg.norm(A @ x_qr - b,ord = 1)/np.linalg.norm(b)
print("QR_upper_bound:",QR_upper_bound)
SVD_upper_bound = (cond_A)*np.linalg.norm(A @ x_svd - b,ord = 1)/np.linalg.norm(b)
print("SVD_upper_bound:",SVD_upper_bound)
LU_lower_bound = (1/cond_A)*np.linalg.norm(A @ x_lu - b,ord = 1)/np.linalg.norm(b)
print("LU_lower_bound:",LU_lower_bound)
QR_lower_bound = (1/cond_A)*np.linalg.norm(A @ x_qr - b,ord = 1)/np.linalg.norm(b)
print("QR_lower_bound:",QR_lower_bound)
SVD_lower_bound = (1/cond_A)*np.linalg.norm(A @ x_svd - b,ord = 1)/np.linalg.norm(b)
print("SVD_lower_bound:",SVD_lower_bound)
# ---------------------------
# 輸出結果
# ---------------------------
print("利用 QR 分解得到的 x =", x_qr)
print("QR residual =", QR_residual)
print("利用 LU 分解得到的 x =", x_lu)
print("LU residual =", LU_residual)
print("利用 SVD 分解得到的 x =", x_svd)
print("SVD residual =", SVD_residual)
print("矩陣 A 的 2-範數條件數 =", cond_A)

# condition number smaller implies the matric is better

LU_upper_bound: 5.5115871827131144e-11
QR_upper_bound: 1.6534761548139342e-10
SVD_upper_bound: 4.4092697461704915e-10
LU_lower_bound: 2.2900435147109546e-19
QR_lower_bound: 6.870130544132864e-19
SVD_lower_bound: 1.8320348117687637e-18
利用 QR 分解得到的 x = [  -4.   60. -180.  140.]
QR residual = [-7.10542736e-15 -7.10542736e-15  7.10542736e-15  0.00000000e+00]
利用 LU 分解得到的 x = [  -4.   60. -180.  140.]
LU residual = [0.00000000e+00 0.00000000e+00 0.00000000e+00 7.10542736e-15]
利用 SVD 分解得到的 x = [  -4.   60. -180.  140.]
SVD residual = [-2.84217094e-14 -1.42108547e-14 -7.10542736e-15 -7.10542736e-15]
矩陣 A 的 2-範數條件數 = 15513.73873892924
